# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "kafji"

  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
    reviewers:
      - "kafji"

  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "weekly"
    reviewers:
      - "kafji"
